title: James Blake
author: Heleen
email: yournotgonnagetit@whatwhat.com
description: > # this means to ignore newlines until "baseurl:"
  In this awesome blog I refer you to James Blake his webpage.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
